"""Synthetic India customer-churn data generator.

Produces 7,000 schema-conformant synthetic records (`docs/PROJECT_SPEC.md`
§3.1, §3.4) from six customer archetypes, each with its own feature
distributions and conditional probabilities — not by copying or jittering
IBM rows (§3.2 point 2). Records are tagged `Source = "India-Synthetic"` and
`CustomerID` prefixed `IN-` for provenance (§3.2 point 1).

Archetypes (target share of the 7,000 records, per §3.4). Same six
segment roles as the Pakistan generator, with India-specific parameter
values (distinct distributions, not a copy of the Pakistan numbers) since
§3.4 specifies the archetype names/shares but leaves distributional detail
to be defined per country, same as Pakistan:

- Metro high-income (15%) — long tenure skew, two-year contracts,
  fiber-equivalent internet, low churn base rate.
- Metro middle-income (25%) — mixed contract types, moderate tenure and
  monthly spend.
- Metro price-sensitive (15%) — month-to-month, DSL or no internet, high
  price sensitivity -> higher churn base rate.
- Semi-urban family plan (15%) — higher partner/dependents rate, multiple
  lines, mid tenure.
- Rural / low connectivity (15%) — lower internet penetration, phone-only
  more common, shorter tenure.
- Young urban single, high-churn segment (15%) — short tenure,
  month-to-month, electronic payment, highest churn base rate.

Distributional assumptions (illustrative, not market research; documented
here per §3.2 point 5): tenure and monthly charges are drawn per-archetype
from truncated-normal distributions clipped to the IBM-observed ranges (0-72
months, $18.25-$118.75); payment-method mix skews toward electronic payment
more heavily than the Pakistan generator across most archetypes (a
documented assumption reflecting a different assumed digital-payment
adoption curve, not empirical research); service add-on uptake is near-zero
in the rural archetype and highest in the high-income and young-urban
archetypes. Total Charges = tenure x monthly charge + billing-variance
noise (§3.3/§3.4), never a perfectly deterministic product.

Churn labels are generated by the shared latent-propensity mechanism in
`engine.py` (`docs/PROJECT_SPEC.md` §3.5): a logistic function of contract
type, charges, tenure, tech support, payment method, and family ties, plus
Gaussian noise and a per-archetype base-churn offset, then sampled as a
Bernoulli draw — so churn is realistic and learnable but never a
deterministic function of any single feature.

Reproducible: `RANDOM_SEED` (`ml/config.py`) drives every draw; re-running
this module produces byte-identical output.

Run directly: `python -m ml.data_generation.india_generator`
"""

from __future__ import annotations

from ml.config import DATA_PROCESSED_DIR, INDIA_SEED, SYNTHETIC_RECORDS_PER_COUNTRY
from ml.data_generation.engine import Archetype, generate_country_dataset

OUTPUT_PATH = DATA_PROCESSED_DIR / "india_synthetic.csv"

ARCHETYPES: list[Archetype] = [
    Archetype(
        name="metro_high_income",
        share=0.15,
        tenure_mean=52,
        tenure_std=15,
        monthly_charges_mean=92,
        monthly_charges_std=16,
        senior_citizen_prob=0.13,
        partner_prob=0.62,
        dependents_prob=0.42,
        phone_service_prob=0.97,
        internet_service_probs={"Fiber optic": 0.70, "DSL": 0.22, "No": 0.08},
        protection_addon_prob=0.58,
        streaming_addon_prob=0.60,
        multiple_lines_prob=0.50,
        contract_probs={"Month-to-month": 0.12, "One year": 0.33, "Two year": 0.55},
        paperless_billing_prob=0.70,
        payment_method_probs={
            "Electronic check": 0.35,
            "Bank transfer (automatic)": 0.25,
            "Credit card (automatic)": 0.25,
            "Mailed check": 0.15,
        },
        churn_base_offset=-1.05,
    ),
    Archetype(
        name="metro_middle_income",
        share=0.25,
        tenure_mean=32,
        tenure_std=15,
        monthly_charges_mean=62,
        monthly_charges_std=17,
        senior_citizen_prob=0.09,
        partner_prob=0.48,
        dependents_prob=0.33,
        phone_service_prob=0.92,
        internet_service_probs={"DSL": 0.40, "Fiber optic": 0.40, "No": 0.20},
        protection_addon_prob=0.40,
        streaming_addon_prob=0.45,
        multiple_lines_prob=0.40,
        contract_probs={"Month-to-month": 0.50, "One year": 0.32, "Two year": 0.18},
        paperless_billing_prob=0.60,
        payment_method_probs={
            "Electronic check": 0.40,
            "Bank transfer (automatic)": 0.22,
            "Credit card (automatic)": 0.18,
            "Mailed check": 0.20,
        },
        churn_base_offset=-0.05,
    ),
    Archetype(
        name="metro_price_sensitive",
        share=0.15,
        tenure_mean=16,
        tenure_std=11,
        monthly_charges_mean=42,
        monthly_charges_std=11,
        senior_citizen_prob=0.07,
        partner_prob=0.38,
        dependents_prob=0.28,
        phone_service_prob=0.88,
        internet_service_probs={"DSL": 0.50, "No": 0.40, "Fiber optic": 0.10},
        protection_addon_prob=0.12,
        streaming_addon_prob=0.20,
        multiple_lines_prob=0.22,
        contract_probs={"Month-to-month": 0.78, "One year": 0.18, "Two year": 0.04},
        paperless_billing_prob=0.45,
        payment_method_probs={
            "Electronic check": 0.40,
            "Mailed check": 0.35,
            "Bank transfer (automatic)": 0.15,
            "Credit card (automatic)": 0.10,
        },
        churn_base_offset=0.65,
    ),
    Archetype(
        name="semi_urban_family",
        share=0.15,
        tenure_mean=36,
        tenure_std=14,
        monthly_charges_mean=58,
        monthly_charges_std=13,
        senior_citizen_prob=0.11,
        partner_prob=0.72,
        dependents_prob=0.68,
        phone_service_prob=0.90,
        internet_service_probs={"DSL": 0.48, "Fiber optic": 0.22, "No": 0.30},
        protection_addon_prob=0.32,
        streaming_addon_prob=0.35,
        multiple_lines_prob=0.60,
        contract_probs={"Month-to-month": 0.38, "One year": 0.38, "Two year": 0.24},
        paperless_billing_prob=0.50,
        payment_method_probs={
            "Mailed check": 0.30,
            "Electronic check": 0.30,
            "Bank transfer (automatic)": 0.22,
            "Credit card (automatic)": 0.18,
        },
        churn_base_offset=-0.30,
    ),
    Archetype(
        name="rural_low_connectivity",
        share=0.15,
        tenure_mean=20,
        tenure_std=13,
        monthly_charges_mean=32,
        monthly_charges_std=9,
        senior_citizen_prob=0.08,
        partner_prob=0.58,
        dependents_prob=0.42,
        phone_service_prob=0.82,
        internet_service_probs={"No": 0.60, "DSL": 0.36, "Fiber optic": 0.04},
        protection_addon_prob=0.08,
        streaming_addon_prob=0.07,
        multiple_lines_prob=0.18,
        contract_probs={"Month-to-month": 0.60, "One year": 0.28, "Two year": 0.12},
        paperless_billing_prob=0.20,
        payment_method_probs={
            "Mailed check": 0.50,
            "Electronic check": 0.25,
            "Bank transfer (automatic)": 0.15,
            "Credit card (automatic)": 0.10,
        },
        churn_base_offset=0.15,
    ),
    Archetype(
        name="young_urban_single_high_churn",
        share=0.15,
        tenure_mean=8,
        tenure_std=6,
        monthly_charges_mean=52,
        monthly_charges_std=14,
        senior_citizen_prob=0.01,
        partner_prob=0.08,
        dependents_prob=0.02,
        phone_service_prob=0.96,
        internet_service_probs={"Fiber optic": 0.55, "DSL": 0.32, "No": 0.13},
        protection_addon_prob=0.14,
        streaming_addon_prob=0.50,
        multiple_lines_prob=0.28,
        contract_probs={"Month-to-month": 0.88, "One year": 0.10, "Two year": 0.02},
        paperless_billing_prob=0.80,
        payment_method_probs={
            "Electronic check": 0.60,
            "Mailed check": 0.12,
            "Bank transfer (automatic)": 0.14,
            "Credit card (automatic)": 0.14,
        },
        churn_base_offset=1.05,
    ),
]


def generate(seed: int = INDIA_SEED):
    return generate_country_dataset(
        archetypes=ARCHETYPES,
        total_records=SYNTHETIC_RECORDS_PER_COUNTRY,
        country_source_label="India-Synthetic",
        id_prefix="IN",
        seed=seed,
    )


def main() -> None:
    df = generate()
    # `_archetype` is internal provenance for validate.py's per-archetype
    # churn-rate table — not part of the schema contract (ML_SPEC.md §1),
    # so it is dropped from the persisted, schema-conformant CSV.
    df = df.drop(columns=["_archetype"])
    DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)
    print(f"Wrote {len(df)} India synthetic records to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
