"""Synthetic Pakistan customer-churn data generator.

Produces 7,000 schema-conformant synthetic records (`docs/PROJECT_SPEC.md`
§3.1, §3.3) from six customer archetypes, each with its own feature
distributions and conditional probabilities — not by copying or jittering
IBM rows (§3.2 point 2). Records are tagged `Source = "Pakistan-Synthetic"`
and `CustomerID` prefixed `PK-` for provenance (§3.2 point 1).

Archetypes (target share of the 7,000 records, per §3.3):

- Urban high-income postpaid-like (15%) — long tenure skew, two-year
  contracts, fiber-equivalent internet, low churn base rate.
- Urban middle-income (25%) — mixed contract types, moderate tenure and
  monthly spend.
- Urban low-income / price-sensitive (15%) — month-to-month, DSL or no
  internet, high price sensitivity -> higher churn base rate.
- Semi-urban family/shared plan (15%) — higher partner/dependents rate,
  multiple lines, mid tenure.
- Rural / lower connectivity (15%) — lower internet penetration, phone-only
  more common, shorter tenure.
- Young single urban, prepaid-like (15%) — short tenure, month-to-month,
  electronic payment, highest churn base rate.

Distributional assumptions (illustrative, not market research; documented
here per §3.2 point 5): tenure and monthly charges are drawn per-archetype
from truncated-normal distributions clipped to the IBM-observed ranges (0-72
months, $18.25-$118.75); payment-method mix is skewed per archetype (e.g.
mailed/electronic check dominate lower-income and rural segments, automatic
bank/card payment is more common in the high-income segment); service add-on
uptake is near-zero in the rural archetype and highest in the high-income and
young-urban archetypes. Total Charges = tenure x monthly charge + billing-
variance noise (§3.3), never a perfectly deterministic product.

Churn labels are generated by the shared latent-propensity mechanism in
`engine.py` (`docs/PROJECT_SPEC.md` §3.5): a logistic function of contract
type, charges, tenure, tech support, payment method, and family ties, plus
Gaussian noise and a per-archetype base-churn offset, then sampled as a
Bernoulli draw — so churn is realistic and learnable but never a
deterministic function of any single feature.

Reproducible: `RANDOM_SEED` (`ml/config.py`) drives every draw; re-running
this module produces byte-identical output.

Run directly: `python -m ml.data_generation.pakistan_generator`
"""

from __future__ import annotations

from pathlib import Path

from ml.config import DATA_PROCESSED_DIR, PAKISTAN_SEED, SYNTHETIC_RECORDS_PER_COUNTRY
from ml.data_generation.engine import Archetype, generate_country_dataset

OUTPUT_PATH = DATA_PROCESSED_DIR / "pakistan_synthetic.csv"

ARCHETYPES: list[Archetype] = [
    Archetype(
        name="urban_high_income",
        share=0.15,
        tenure_mean=55,
        tenure_std=14,
        monthly_charges_mean=95,
        monthly_charges_std=15,
        senior_citizen_prob=0.14,
        partner_prob=0.65,
        dependents_prob=0.45,
        phone_service_prob=0.97,
        internet_service_probs={"Fiber optic": 0.75, "DSL": 0.20, "No": 0.05},
        protection_addon_prob=0.60,
        streaming_addon_prob=0.55,
        multiple_lines_prob=0.55,
        contract_probs={"Month-to-month": 0.10, "One year": 0.30, "Two year": 0.60},
        paperless_billing_prob=0.65,
        payment_method_probs={
            "Bank transfer (automatic)": 0.30,
            "Credit card (automatic)": 0.35,
            "Electronic check": 0.20,
            "Mailed check": 0.15,
        },
        churn_base_offset=-1.10,
    ),
    Archetype(
        name="urban_middle_income",
        share=0.25,
        tenure_mean=34,
        tenure_std=16,
        monthly_charges_mean=65,
        monthly_charges_std=18,
        senior_citizen_prob=0.10,
        partner_prob=0.50,
        dependents_prob=0.35,
        phone_service_prob=0.93,
        internet_service_probs={"DSL": 0.45, "Fiber optic": 0.35, "No": 0.20},
        protection_addon_prob=0.40,
        streaming_addon_prob=0.40,
        multiple_lines_prob=0.45,
        contract_probs={"Month-to-month": 0.45, "One year": 0.35, "Two year": 0.20},
        paperless_billing_prob=0.55,
        payment_method_probs={
            "Electronic check": 0.30,
            "Mailed check": 0.25,
            "Bank transfer (automatic)": 0.25,
            "Credit card (automatic)": 0.20,
        },
        churn_base_offset=-0.10,
    ),
    Archetype(
        name="urban_low_income_price_sensitive",
        share=0.15,
        tenure_mean=18,
        tenure_std=12,
        monthly_charges_mean=45,
        monthly_charges_std=12,
        senior_citizen_prob=0.08,
        partner_prob=0.40,
        dependents_prob=0.30,
        phone_service_prob=0.90,
        internet_service_probs={"DSL": 0.55, "No": 0.35, "Fiber optic": 0.10},
        protection_addon_prob=0.15,
        streaming_addon_prob=0.15,
        multiple_lines_prob=0.25,
        contract_probs={"Month-to-month": 0.75, "One year": 0.20, "Two year": 0.05},
        paperless_billing_prob=0.40,
        payment_method_probs={
            "Electronic check": 0.35,
            "Mailed check": 0.40,
            "Bank transfer (automatic)": 0.15,
            "Credit card (automatic)": 0.10,
        },
        churn_base_offset=0.60,
    ),
    Archetype(
        name="semi_urban_family",
        share=0.15,
        tenure_mean=38,
        tenure_std=15,
        monthly_charges_mean=60,
        monthly_charges_std=14,
        senior_citizen_prob=0.12,
        partner_prob=0.75,
        dependents_prob=0.70,
        phone_service_prob=0.92,
        internet_service_probs={"DSL": 0.50, "Fiber optic": 0.25, "No": 0.25},
        protection_addon_prob=0.35,
        streaming_addon_prob=0.30,
        multiple_lines_prob=0.65,
        contract_probs={"Month-to-month": 0.35, "One year": 0.40, "Two year": 0.25},
        paperless_billing_prob=0.45,
        payment_method_probs={
            "Mailed check": 0.35,
            "Electronic check": 0.25,
            "Bank transfer (automatic)": 0.25,
            "Credit card (automatic)": 0.15,
        },
        churn_base_offset=-0.35,
    ),
    Archetype(
        name="rural_low_connectivity",
        share=0.15,
        tenure_mean=22,
        tenure_std=14,
        monthly_charges_mean=35,
        monthly_charges_std=10,
        senior_citizen_prob=0.09,
        partner_prob=0.55,
        dependents_prob=0.40,
        phone_service_prob=0.85,
        internet_service_probs={"No": 0.55, "DSL": 0.40, "Fiber optic": 0.05},
        protection_addon_prob=0.10,
        streaming_addon_prob=0.05,
        multiple_lines_prob=0.20,
        contract_probs={"Month-to-month": 0.55, "One year": 0.30, "Two year": 0.15},
        paperless_billing_prob=0.25,
        payment_method_probs={
            "Mailed check": 0.55,
            "Electronic check": 0.20,
            "Bank transfer (automatic)": 0.15,
            "Credit card (automatic)": 0.10,
        },
        churn_base_offset=0.10,
    ),
    Archetype(
        name="young_single_urban_prepaid_like",
        share=0.15,
        tenure_mean=9,
        tenure_std=7,
        monthly_charges_mean=55,
        monthly_charges_std=15,
        senior_citizen_prob=0.01,
        partner_prob=0.10,
        dependents_prob=0.03,
        phone_service_prob=0.95,
        internet_service_probs={"Fiber optic": 0.50, "DSL": 0.35, "No": 0.15},
        protection_addon_prob=0.15,
        streaming_addon_prob=0.45,
        multiple_lines_prob=0.30,
        contract_probs={"Month-to-month": 0.85, "One year": 0.12, "Two year": 0.03},
        paperless_billing_prob=0.75,
        payment_method_probs={
            "Electronic check": 0.55,
            "Mailed check": 0.15,
            "Bank transfer (automatic)": 0.15,
            "Credit card (automatic)": 0.15,
        },
        churn_base_offset=1.00,
    ),
]


def generate(seed: int = PAKISTAN_SEED):
    return generate_country_dataset(
        archetypes=ARCHETYPES,
        total_records=SYNTHETIC_RECORDS_PER_COUNTRY,
        country_source_label="Pakistan-Synthetic",
        id_prefix="PK",
        seed=seed,
    )


def main() -> None:
    df = generate()
    # `_archetype` is internal provenance for validate.py's per-archetype
    # churn-rate table — not part of the schema contract (ML_SPEC.md §1),
    # so it is dropped from the persisted, schema-conformant CSV.
    df = df.drop(columns=["_archetype"])
    DATA_PROCESSED_DIR.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUTPUT_PATH, index=False)
    print(f"Wrote {len(df)} Pakistan synthetic records to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
