from __future__ import annotations

import os
import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# So `backend.db.models`/`backend.db.session` import cleanly whether Alembic
# is invoked from the repo root or from `backend/` (`docs/DATABASE_SPEC.md` §7).
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from backend.db.base import Base  # noqa: E402
from backend.db.models import *  # noqa: E402,F401,F403 — registers every table on Base.metadata
from backend.db.session import default_database_url  # noqa: E402

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers=False`: the stdlib default (True) disables
    # every already-created logger not explicitly listed in alembic.ini's
    # `[loggers]` section -- including the app's own `churnai.*` loggers,
    # which are already alive by the time this runs (imported transitively
    # via `backend.app` before any test/migration executes). Left at the
    # default, every `alembic upgrade` silently kills app logging for the
    # rest of the process.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def _database_url() -> str:
    return os.environ.get("DATABASE_URL", default_database_url())


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    configuration = config.get_section(config.config_ini_section) or {}
    configuration["sqlalchemy.url"] = _database_url()
    connectable = engine_from_config(configuration, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        # `render_as_batch`: SQLite can't ALTER a column/constraint in place;
        # batch mode recreates the table under the hood so future
        # autogenerated migrations (e.g. altering a CHECK constraint) work
        # against SQLite the same way they would against PostgreSQL.
        context.configure(connection=connection, target_metadata=target_metadata, render_as_batch=True)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
